package com.tinkerpop.blueprints.util.wrappers.event2.listener;

import java.util.Iterator;

/**
 * An event generated by changes to the graph.
 */
public interface Event {

    public void fireEvent(Iterator<GraphChangedListener> eventListeners);

}
